🚨 core: Use a slice instead of Vec
This satisfies a clippy lint:

```rust
error: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
   --> zlink-core/src/server/mod.rs:159:18
    |
159 |           readers: &'r mut Vec<
    |  __________________^
160 | |             ReadConnection<<<Listener as crate::Listener>::Socket as Socket>::ReadHalf>,
161 | |         >,
    | |_________^ help: change this to: `&'r mut [ReadConnection<<<Listener as crate::Listener>::Socket as Socket>::ReadHalf>]`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
    = note: `-D clippy::ptr-arg` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::ptr_arg)]`
```